# Generated by Django 2.0.6 on 2018-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howToPrepare', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
