# Generated by Django 2.0.6 on 2018-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='timeToPrepare',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='howToPrepare',
            field=models.TextField(default=''),
        ),
    ]
