# Generated by Django 2.0.6 on 2018-06-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180615_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ingridient'),
        ),
    ]
