# Generated by Django 2.0.6 on 2018-06-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180615_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingridients', to='api.Recipe'),
        ),
    ]
